Feature: E2E - Task Toaster InvoiceEngine.PreInvoiceValidationMap task (Startex Client)

    // Auto generated by aurea-automation - util on Fri, 24 Sep 2019 13:17:57 GMT
    @HealthCheckSuite
    Scenario: [Startex] User is able to execute "InvoiceEngine.PreInvoiceValidationMap" task in Task Toaster website - [C25738083]
        Given Login to "${taskToasterStaging.url}" with userName : "${stagingCsr.userName}" and password : "${stagingCsr.password}"
        Then Task toaster app is logged in

        When Navigate to URL "${taskToasterStaging.url}" /Task/Settings/425
        Then Tasks Dashboard page is loaded

        When Execute Task for Startex Power Client
        Then Verify task to finished

        When Click to Startex Power tab
        Then Verify Log Items loaded

        When Click To Search Button To Refresh Logs
        Then Verify Log Items loaded

        And Verify Log Items for Started
        And Verify Log Items for Complete
