Feature: E2E for Feature Story AESCIS-37827 - search.aspx(Accent)
    // Auto generated by aurea-automation - util on Thu, 19 Sep 2019 16:29:11 GMT

    Background:
        Given Generic logout
        And user navigates to URL : "${accentStagingWebsiteV3.url}" application

    @SmokeSuite
    Scenario: TC01 - User is able to search accounts using "Premise Zip", "Last Name" and "First Name" fields for Accent client - [25717447]
        Given Login page loaded
        When fill userName : "${stagingCsr.userName}"
        And fill password : "${stagingCsr.password}"
        And hit login button at StreamStaginCSR login page
        Then home page of StreamStagingCSR should open

        When Click to Customer Search
        Then home page of StreamStagingCSR should open

        When Enter PremiseZip as "111"
        And Click Search Button
        Then Check Show Results
        And Verify Results for "111"

        When Enter Last Name as "A"
        And Click Search Button
        Then Check Show Results
        And Verify Results for "111"
        And Verify Results for "A"

        When Enter First Name as "B"
        And Click Search Button
        Then Check Show Results
        And Verify Results for "111"
        And Verify Results for "A"
        And Verify Results for "B"
