Feature: E2E for Feature Story AESCIS-37847 - latefeereversal.aspx (Stream)
    // Auto generated by aurea-automation - util on Tue, 17 Sep 2019 17:07:13 GMT

    Background:
        Given Generic logout
        And user navigates to URL : "${streamStagingWebsite.url}" application

    @SmokeSuite
    Scenario: User is able to verify the latefeereversal.aspx page in StreamEnergy Application - [C25726270]
        Given Login page loaded
        When fill userName : "${stagingCsr.userName}"
        And fill password : "${stagingCsr.password}"
        And hit login button at StreamStaginCSR login page

        When Navigate to URL-> "${streamDomainStagingWebsite.url}" Callcenter CustomerSummary
        Then Customer summary page is loaded

        When Select ARBilling Tab fin in grid row
        And Click to Reversal button
        Then Reversal Popup opened

        When Click to Close button
        Then Customer summary page is loaded

        When Click to Reversal button
        Then Reversal Popup opened
        When Click to Cancel button
        Then Customer summary page is loaded

        When Click to Reversal button
        Then Reversal Popup opened
        When Click to Save button
        Then Customer summary page is loaded
