Feature: E2E for Feature Story AESCIS-37839 - BudgetBillingEdit.aspx (Stream)
    // Auto generated by aurea-automation - util on Thu, 19 Sep 2019 13:21:32 GMT

    Background:
        Given Generic logout
        And user navigates to URL : "${streamStagingWebsite.url}" application

    @SmokeSuite
    Scenario: User verifies the BudgetBillingEdit.aspx page (Stream) - [25722498]
        Given Login page loaded
        When fill userName : "${stagingCsr.userName}"
        And fill password : "${stagingCsr.password}"
        And hit login button at StreamStaginCSR login page

        When Navigate to URL-> "${streamDomainStagingWebsite.url}" Callcenter CustomerSummary
        Then Customer summary page is loaded

        Then Check Balance Table for "Balance"
        And Check Balance Table for "Current"
        And Check Balance Table for "1-30"
        And Check Balance Table for "31-60"
        And Check Balance Table for "AR Terms (Days)"
        And Check Balance Table for "Budget Billing"
        And Check Balance Table for "Budget Variance"

        When Note down the value "Budget Billing"
        And Click Calculator
        Then Verify Budget Billing Details Page
        And Verify Customer Name is "Josephine Jones"
        And Verify the value Noted before
